/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sdzee_pricing_compute */

#ifndef _Included_com_sdzee_pricing_compute
#define _Included_com_sdzee_pricing_compute
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sdzee_pricing_compute
 * Method:    computePrices
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sdzee_pricing_compute_computePrices
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
